---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["python3-pip", "nginx", "gunicorn"]
    state: latest
    update_cache: yes