---
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "creates directory"
  become: yes
  file:
    path: /home/ubuntu/flaskapp
    state: directory

- name: "Copy backend tar.gz file and unzipping it"
  become: yes
  unarchive:
    src: ~/project/flaskapp.tar.gz
    dest: /home/ubuntu/flaskapp

- name: "copy flaskapp to nginx config"
  become: yes
  copy:
    src: "files/flaskapp"
    dest: "/etc/nginx/sites-enabled/flaskapp"

- name: "installing requirements"
  shell: pip3 install -r requirements.txt
  args:
    chdir: /home/ubuntu/flaskapp

- name: "Copy gunicorn.service to systemd"
  become: yes
  copy:
    src: "files/gunicorn.service"
    dest: "/etc/systemd/system/gunicorn.service"

- name: "reload daemon"
  become: yes
  systemd:
    daemon_reload: yes

- name: "enable gunicorn service"
  become: yes
  service:
    name: gunicorn.service
    enabled: yes
    state: started

- name: "restarting nginx server"
  become: yes
  service:
    name: nginx
    state: restarted