---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade package"
  become: yes
  apt:
    upgrade: 'yes'

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["python3-pip", "nginx", "gunicorn"]
    state: latest
    update_cache: yes