AWSTemplateFormatVersion: "2010-09-09"
Description: Docking the clouds backend stack
Parameters:
  ID:
    Description: Unique identifier
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22, 80 and 443.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: CA-KeyPair
      ImageId: ami-00831fc7c1e3ddc60
      Tags:
        - Key: Name
          Value: !Sub dtc-backend-${ID}

  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref EC2Instance
      AllocationId: eipalloc-10d36721

Outputs:
  WorkflowID:
    Value: !Sub ${ID}
    Description: Workflow Id
    Export:
      Name: dtc-WorkflowID